FROM tensorflow/tensorflow

WORKDIR .

COPY . .

# Upgrade pip:
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install --upgrade --quiet duckduckgo-search


EXPOSE 8000
# Populate the vector DB if need:
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]